# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-15 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('quialification_id', models.IntegerField(primary_key=True, serialize=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diquecito.Post')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.IntegerField(primary_key=True, serialize=False)),
                ('duration', models.TimeField()),
                ('cost', models.FloatField(blank=True, null=True)),
                ('payment_method_choices', models.CharField(choices=[('MP', 'Mercado Pago')], max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='qualification',
            name='reservation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diquecito.Reservation'),
        ),
    ]
