# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-16 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diquecito', '0003_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ususario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
            ],
        ),
    ]
