# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-16 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diquecito', '0005_auto_20190516_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='id',
        ),
        migrations.AddField(
            model_name='usuario',
            name='usuario_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
