# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-16 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diquecito', '0006_auto_20190516_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='usuario_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
