# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-16 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diquecito', '0009_auto_20190516_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='quialification_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
