# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-16 16:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diquecito', '0010_auto_20190516_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qualification',
            old_name='post',
            new_name='post_id',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='reservation_id',
        ),
    ]
