# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-21 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diquecito', '0011_auto_20190516_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qualification',
            old_name='post_id',
            new_name='post_f',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
