# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-21 11:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diquecito', '0012_auto_20190521_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='usuario_f',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diquecito.Usuario'),
        ),
    ]
