# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-21 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diquecito', '0013_post_usuario_f'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=20, null=True),
        ),
    ]
