# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-21 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diquecito', '0016_auto_20190521_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='vote_choices',
            field=models.CharField(blank=True, choices=[('1', 'one'), ('2', 'two'), ('3', 'three'), ('4', 'four'), ('5', 'five')], default=1, max_length=2, null=True, unique=True),
        ),
    ]
