# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-21 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diquecito', '0017_qualification_vote_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='vote_choices',
            field=models.IntegerField(blank=True, choices=[(1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five')], default=1, null=True, unique=True),
        ),
    ]
