# Generated by Django 2.2.2 on 2019-06-11 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diquecito', '0018_auto_20190521_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_id',
        ),
        migrations.RemoveField(
            model_name='post',
            name='usuario_f',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='post_f',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='quialification_id',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='reservation_id',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='usuario_id',
        ),
        migrations.AddField(
            model_name='post',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='usuario_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Usuario', to='diquecito.Usuario'),
        ),
        migrations.AddField(
            model_name='qualification',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qualification',
            name='post_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='diquecito.Post'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
