# Generated by Django 2.2.2 on 2019-06-15 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diquecito', '0019_auto_20190611_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='usuario_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='diquecito.Usuario'),
        ),
    ]
